export const EMAIL_DOMAINS = [
    "gmail.com",
    "yahoo.com",
    "hotmail.com",
    "aol.com",
    "outlook.com",
    "comcast.net",
    "icloud.com",
    "yandex.ru",
    "mail.ru" ,
    "msn.com",
    "hotmail.co.uk",
    "sbcglobal.net", 
    "live.com",
    "yahoo.co.in",
    "me.com",
    "att.net", 
    "bellsouth.net",
    "rediffmail.com",
    "cox.net",
    "yahoo.co.uk",
    "verizon.net",
    "ymail.com",
    "hotmail.it",
    "kw.com",
    "yahoo.com.tw",
    "mac.com",
    "live.se",
    "live.nl",
    "yahoo.com.br",
    "googlemail.com",
    "libero.it",
    "web.de",
    "allstate.com",
    "btinternet.com",
    "online.no",
    "yahoo.com.au", 
    "rocketmail.com",
    "gmx.at",
    "mail.com",
    "yahoo.in",
    "qq.com",
    "alice.it",
    "morganstanley.com",
    "anz.com",
    "inbox.ru",
    "bk.ru",
    "list.ru",
    "rambler.ru",
    "ya.ru",
    "vk.ru",
    "internet.ru",
  ] as const;
  
  export const DOMAIN_HINTS = [
    "gmail.com",
    "yandex.ru",
    "outlook.com",
    "mail.ru"
  ] as const;